name: Force Delete AWS Resources

on:
  workflow_dispatch:  # Manual trigger

env:
  AWS_REGION: us-east-2
  CLUSTER_NAME: task9-strapi-cluster-aviral
  SERVICE_NAME: aviral-strapi-service-task9
  TASK_FAMILY: strapi-task
  TG_NAME: aviral-strapi-tg-task9
  ALB_NAME: aviral-strapi-alb-task9
  LOG_GROUP: /ecs/strapi-task-aviral-task9
  SG_NAME: aviral-strapi-ecs-sg
  ECR_REPO: strapi-app-aviral

jobs:
  force-delete:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Delete ECS Service & Cluster
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --desired-count 0 || true
        sleep 15
        aws ecs delete-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force || true
        aws ecs delete-cluster --cluster $CLUSTER_NAME || true

    - name: Delete Task Definitions
      run: |
        for arn in $(aws ecs list-task-definitions --family-prefix $TASK_FAMILY --query "taskDefinitionArns[]" --output text); do
          aws ecs deregister-task-definition --task-definition "$arn" || true
        done

    - name: Delete ALB and Target Group
      run: |
        TG_ARN=$(aws elbv2 describe-target-groups --names $TG_NAME --query "TargetGroups[0].TargetGroupArn" --output text)
        ALB_ARN=$(aws elbv2 describe-load-balancers --names $ALB_NAME --query "LoadBalancers[0].LoadBalancerArn" --output text)

        if [ "$ALB_ARN" != "None" ]; then
          LISTENER_ARN=$(aws elbv2 describe-listeners --load-balancer-arn $ALB_ARN --query "Listeners[0].ListenerArn" --output text)
          aws elbv2 delete-listener --listener-arn $LISTENER_ARN || true
          aws elbv2 delete-load-balancer --load-balancer-arn $ALB_ARN || true
        fi

        if [ "$TG_ARN" != "None" ]; then
          aws elbv2 delete-target-group --target-group-arn $TG_ARN || true
        fi

    - name: Delete CloudWatch Logs
      run: |
        aws logs delete-log-group --log-group-name $LOG_GROUP || true

    - name: Delete Security Groups
      run: |
        SG_ID=$(aws ec2 describe-security-groups --filters Name=group-name,Values=$SG_NAME --query "SecurityGroups[0].GroupId" --output text)
        if [ "$SG_ID" != "None" ]; then
          aws ec2 delete-security-group --group-id $SG_ID || true
        fi

    - name: Delete all ECR Images (but keep repo)
      run: |
        IMAGE_IDS=$(aws ecr list-images --repository-name $ECR_REPO --query 'imageIds[*]' --output json)
        if [ "$IMAGE_IDS" != "[]" ]; then
          aws ecr batch-delete-image --repository-name $ECR_REPO --image-ids "$IMAGE_IDS" || true
        fi