name: Force Delete AWS Resources

on:
  workflow_dispatch:  # Manual trigger

env:
  AWS_REGION: us-east-2
  CLUSTER_NAME: task11-strapi-cluster-aviral
  BLUE_SERVICE_NAME: strapi-service-blue
  GREEN_SERVICE_NAME: strapi-service-green
  TASK_FAMILY: aviral-strapi-task
  TG_BLUE_NAME: aviral-tg-blue-11
  TG_GREEN_NAME: aviral-tg-green-11
  ALB_NAME: aviral-strapi-alb-task11
  LOG_GROUP: /ecs/strapi-task-aviral-task11
  SG_NAME: aviral-strapi-ecs-sg
  ECR_REPO: strapi-app-aviral
  CODEDEPLOY_APP: StrapiCodeDeployApp-aviral
  CODEDEPLOY_GROUP: StrapiDeployGroup-avi

jobs:
  terraform-destroy:
    name: Terraform Destroy (Strapi Infra)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Download tfstate artifact
        uses: actions/download-artifact@v4
        with:
          name: tfstate-artifact
          path: ./terraform8

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve