name: CD - Deploy with Terraform

on:
  workflow_run:
    workflows: ["CI pipeline - Build & Push Docker Image"]  
    types:
      - completed

permissions:
  actions: read
  contents: read
  
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3  
        with:
          workflow: ci.yaml
          name: image-tag
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image tag
        id: image_tag
        run: echo "tag=latest" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: terraform2_task5/

      - name: Terraform Apply
        working-directory: terraform2_task5/
        run: |
          terraform apply -auto-approve \
            -var="image_tag=latest" \
            -var="ami_id=ami-0d1b5a8c13042c939" \
            -var="key_name=strapi-tohid" \
            -var="aws_region=us-east-2" \
            -var="instance_type=t2.micro" \