name: Trigger CodeDeploy Deployment

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  CODEDEPLOY_APP: strapi-app-deploy
  CODEDEPLOY_GROUP: StrapiDeployGroup-avi
  TASK_REVISION: strapi-task-family  # Must match your ECS task family

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get Latest Task Definition ARN
      id: taskdef
      run: |
        LATEST_ARN=$(aws ecs list-task-definitions --family-prefix $TASK_REVISION --sort DESC --max-items 1 --query "taskDefinitionArns[0]" --output text)
        echo "LATEST_TASK_DEF=$LATEST_ARN" >> $GITHUB_ENV
        echo "Latest task def: $LATEST_ARN"

    - name: Trigger Deployment via CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name $CODEDEPLOY_APP \
          --deployment-group-name $CODEDEPLOY_GROUP \
          --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
          --description "Triggered from GitHub Actions" \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
          --file-exists-behavior OVERWRITE \
          --revision revisionType=AppSpecContent,appSpecContent={content="{\"version\":\"1.0\",\"Resources\":[{\"TargetService\":{\"Type\":\"AWS::ECS::Service\",\"Properties\":{\"TaskDefinition\":\"$LATEST_TASK_DEF\",\"LoadBalancerInfo\":{\"ContainerName\":\"strapi\",\"ContainerPort\":1337}}}}]"}
